name = "ruae2"
main = "worker.js"
compatibility_date = "2026-02-14"
workers_dev = true
account_id = "be86a6ded4d9f79bf1597fe22adbb4b7"

[[d1_databases]]
binding = "DB"
database_name = "ruae-members-db"
database_id = "6f9e29c4-1a9f-4927-9e63-c70cb1a653e7"

[[routes]]
pattern = "api.rishisubjects.co.uk"
custom_domain = true

[vars]
ALLOWED_ORIGINS = "https://rishisubjects.co.uk,https://www.rishisubjects.co.uk,https://rishisubjects.pages.dev"
PAGES_PROJECT_NAME = "rishisubjects"
REQUIRE_MANUAL_APPROVAL = "true"
ALLOW_LOCALHOST_ORIGINS = "true"
